name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@122.51.133.41 "
            cd /root/Mooyu &&
            git pull origin main &&
            npm install &&
            pm2 restart mooyu
          " 